# Generated by Django 3.0.6 on 2020-06-01 18:18

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('events', '0001_initial'),
        ('home', '0001_initial'),
        ('wagtailimages', '0022_uploadedimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='partitioneventpage',
            name='partition',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='home.Partition', verbose_name='Partition'),
        ),
        migrations.AddField(
            model_name='instrumenteventpage',
            name='instrument',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='home.Instrument', verbose_name='Instrument'),
        ),
        migrations.AddField(
            model_name='instrumenteventpage',
            name='page',
            field=modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_instruments', to='events.EventCalPage'),
        ),
        migrations.AddField(
            model_name='eventcalpage',
            name='categories',
            field=models.ManyToManyField(blank=True, help_text='Categories this event belongs to', through='events.CategoryEventPage', to='events.Category', verbose_name='Categories'),
        ),
        migrations.AddField(
            model_name='eventcalpage',
            name='image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image', verbose_name='Image'),
        ),
        migrations.AddField(
            model_name='eventcalpage',
            name='instruments',
            field=models.ManyToManyField(blank=True, help_text='Instruments this event belongs to', through='events.InstrumentEventPage', to='home.Instrument', verbose_name='Instruments'),
        ),
        migrations.AddField(
            model_name='eventcalpage',
            name='partitions',
            field=models.ManyToManyField(blank=True, help_text='Partitions this event belongs to', through='events.PartitionEventPage', to='home.Partition', verbose_name='Partitions'),
        ),
        migrations.AddField(
            model_name='eventcalendar',
            name='default_image',
            field=models.ForeignKey(blank=True, help_text='Default image to be used for calendar entries', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image', verbose_name='Default Image'),
        ),
        migrations.AddField(
            model_name='categoryeventpage',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='events.Category', verbose_name='Category'),
        ),
        migrations.AddField(
            model_name='categoryeventpage',
            name='page',
            field=modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_categories', to='events.EventCalPage'),
        ),
        migrations.AddField(
            model_name='category',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='events.Category', verbose_name='Parent category'),
        ),
    ]
