# Generated by Django 3.0.6 on 2020-06-25 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_auto_20200601_2018'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventcalendar',
            name='heading',
            field=models.CharField(default=1, max_length=65),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='eventcalendar',
            name='subheading',
            field=models.CharField(default=1, max_length=65),
            preserve_default=False,
        ),
    ]
