# Generated by Django 3.0.6 on 2020-06-30 13:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_auto_20200625_1044'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventcalpage',
            name='partitions',
        ),
        migrations.DeleteModel(
            name='PartitionEventPage',
        ),
    ]
