# Generated by Django 3.0.6 on 2020-06-01 18:38

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarouselElementHomePage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('carouselelement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='home.CarouselElement', verbose_name='Carousel Element')),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='home_carouselelements', to='home.HomePage')),
            ],
        ),
        migrations.AddField(
            model_name='homepage',
            name='carouselelements',
            field=models.ManyToManyField(blank=True, help_text='belongs to', through='home.CarouselElementHomePage', to='home.CarouselElement', verbose_name='Carousel Elements'),
        ),
    ]
