# Generated by Django 3.0.6 on 2020-06-04 11:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20200601_2038'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carouselelementhomepage',
            name='carouselelement',
        ),
        migrations.RemoveField(
            model_name='carouselelementhomepage',
            name='page',
        ),
        migrations.RenameField(
            model_name='homepage',
            old_name='cardimage4',
            new_name='image4',
        ),
        migrations.RenameField(
            model_name='homepage',
            old_name='cardtext4',
            new_name='text4',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='carouselelements',
        ),
        migrations.DeleteModel(
            name='CarouselElement',
        ),
        migrations.DeleteModel(
            name='CarouselElementHomePage',
        ),
    ]
