# Generated by Django 3.0.6 on 2020-09-03 15:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailmenus', '0023_remove_use_specific'),
        ('wagtailcore', '0045_assign_unlock_grouppagepermission'),
        ('events', '0003_auto_20200903_1547'),
        ('wagtailforms', '0004_add_verbose_name_plural'),
        ('wagtailredirects', '0006_redirect_increase_max_length'),
        ('home', '0002_auto_20200821_1004'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='participation',
            name='event_page',
        ),
        migrations.RemoveField(
            model_name='participation',
            name='instrument',
        ),
        migrations.RemoveField(
            model_name='participation',
            name='user',
        ),
        migrations.DeleteModel(
            name='BookPage',
        ),
        migrations.DeleteModel(
            name='Instrument',
        ),
        migrations.DeleteModel(
            name='Participation',
        ),
    ]
