# Generated by Django 3.0.6 on 2020-06-05 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_remove_homepage_image4'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homepage',
            name='text4',
        ),
        migrations.AddField(
            model_name='homepage',
            name='invitation',
            field=models.TextField(blank=True, help_text='Invitation à la connexion'),
        ),
    ]
