# Generated by Django 3.0.6 on 2020-06-05 15:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailredirects', '0006_redirect_increase_max_length'),
        ('wagtailmenus', '0023_remove_use_specific'),
        ('wagtailforms', '0004_add_verbose_name_plural'),
        ('wagtailcore', '0045_assign_unlock_grouppagepermission'),
        ('home', '0008_partitionsindexpage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='videosindexpage',
            name='image',
        ),
        migrations.RemoveField(
            model_name='videosindexpage',
            name='page_ptr',
        ),
        migrations.RemoveField(
            model_name='videosindexpage',
            name='videos',
        ),
        migrations.DeleteModel(
            name='PartitionsIndexPage',
        ),
        migrations.DeleteModel(
            name='VideosIndexPage',
        ),
    ]
