# Generated by Django 3.0.6 on 2020-06-05 15:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailredirects', '0006_redirect_increase_max_length'),
        ('wagtailmenus', '0023_remove_use_specific'),
        ('wagtailcore', '0045_assign_unlock_grouppagepermission'),
        ('wagtailforms', '0004_add_verbose_name_plural'),
        ('home', '0010_partitionsindexpage_videosindexpage'),
    ]

    operations = [
        migrations.DeleteModel(
            name='VideosIndexPage',
        ),
    ]
