# Generated by Django 3.0.6 on 2020-06-05 16:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_bookpage'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookpage',
            name='partition',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='home.Partition'),
        ),
    ]
