# Generated by Django 3.0.6 on 2020-06-07 07:31

from django.db import migrations
import wagtail.core.fields
import wagtail.embeds.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0019_videosindexpage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videosindexpage',
            name='body',
            field=wagtail.core.fields.StreamField([('embedded_video', wagtail.embeds.blocks.EmbedBlock(icon='media'))], blank=True),
        ),
    ]
