# Generated by Django 3.0.6 on 2020-06-13 07:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home', '0021_trombipiece'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trombipiece',
            name='title',
        ),
        migrations.AddField(
            model_name='trombipiece',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
