# Generated by Django 3.0.6 on 2020-06-23 16:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0022_auto_20200613_0906'),
    ]

    operations = [
        migrations.RenameField(
            model_name='aboutpage',
            old_name='cardtext2',
            new_name='invitation',
        ),
        migrations.RemoveField(
            model_name='aboutpage',
            name='cardimage2',
        ),
        migrations.RemoveField(
            model_name='aboutpage',
            name='cardimage3',
        ),
        migrations.RemoveField(
            model_name='aboutpage',
            name='cardimage4',
        ),
        migrations.RemoveField(
            model_name='aboutpage',
            name='cardtext3',
        ),
        migrations.RemoveField(
            model_name='aboutpage',
            name='cardtext4',
        ),
    ]
