# Generated by Django 3.0.6 on 2020-06-25 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0023_auto_20200623_1838'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutpage',
            name='heading',
            field=models.CharField(default=1, max_length=65),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='aboutpage',
            name='subheading',
            field=models.CharField(default=1, max_length=65),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='partition',
            name='subtitle',
            field=models.CharField(default=1, max_length=65),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='partition',
            name='title',
            field=models.CharField(max_length=65),
        ),
    ]
