# Generated by Django 3.0.6 on 2020-06-25 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0024_auto_20200625_0919'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='formpage',
            name='image',
        ),
        migrations.AddField(
            model_name='formpage',
            name='heading',
            field=models.CharField(default=1, max_length=65),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='formpage',
            name='subheading',
            field=models.CharField(default=1, max_length=65),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='formpage',
            name='thank_you_text',
            field=models.TextField(blank=True, help_text='Remerciements'),
        ),
    ]
