# Generated by Django 3.0.6 on 2020-06-25 19:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0026_auto_20200625_0953'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, unique=True, verbose_name='Category name')),
            ],
            options={
                'verbose_name': 'Partition Category',
                'verbose_name_plural': 'Partition Categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='CategoryPartition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='home.Category', verbose_name='Category')),
                ('partition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partition_categories', to='home.Partition')),
            ],
        ),
        migrations.AddField(
            model_name='partition',
            name='categories',
            field=models.ManyToManyField(blank=True, help_text='Categories this PARTITION belongs to', through='home.CategoryPartition', to='home.Category', verbose_name='Categories'),
        ),
    ]
