# Generated by Django 3.0.6 on 2020-06-25 22:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0027_auto_20200625_1928'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='partition',
            name='categories',
        ),
        migrations.AddField(
            model_name='partition',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='home.Category'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='CategoryPartition',
        ),
    ]
