# Generated by Django 3.0.6 on 2020-06-30 13:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailredirects', '0006_redirect_increase_max_length'),
        ('wagtailmenus', '0023_remove_use_specific'),
        ('wagtailforms', '0004_add_verbose_name_plural'),
        ('wagtailcore', '0045_assign_unlock_grouppagepermission'),
        ('home', '0028_auto_20200625_2206'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PartitionsIndexPage',
        ),
    ]
