# Generated by Django 3.0.6 on 2020-06-30 13:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_auto_20200630_1339'),
        ('home', '0029_delete_partitionsindexpage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='partition',
            name='category',
        ),
        migrations.RemoveField(
            model_name='bookpage',
            name='partition',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.DeleteModel(
            name='Partition',
        ),
    ]
